{{- if .Values.enabled }}
kind: ConfigMap
metadata:
  name: {{ include "newrelic.common.naming.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
apiVersion: v1
data:
  config.yaml: |
    cluster_name: {{ include "newrelic.common.cluster" . }}
{{- if .Values.config -}}
  {{- if and (.Values.config.transformations) (include "newrelic.common.lowDataMode" .) -}}
    {{- include "nri-prometheus.mergeTransformations" . -}}
  {{- else if (include "newrelic.common.lowDataMode" .) -}}
    {{/* When lowDataMode is enabled without custom transformations, merge config with defaults */}}
    {{ $lowDataDefault := .Files.Get "static/lowdatamodedefaults.yaml" | fromYaml }}
    {{ $mergedConfig := mergeOverwrite (deepCopy .Values.config) $lowDataDefault }}
    {{- omit $mergedConfig "transformations" | toYaml | nindent 4 -}}
    {{/* Render transformations array from lowDataMode defaults */}}
    transformations:
    {{- $lowDataDefault.transformations | toYaml | nindent 4 -}}
  {{- else }}
    {{- .Values.config | toYaml | nindent 4  -}}
  {{- end -}}
{{- end -}}
{{- end }}
