apiVersion: v2
name: nri-prometheus
description: A Helm chart to deploy the New Relic Prometheus OpenMetrics integration
home: https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-openmetrics/configure-prometheus-openmetrics-integrations/
icon: https://newrelic.com/themes/custom/curio/assets/mediakit/new_relic_logo_vertical.svg
sources:
  - https://github.com/newrelic/nri-prometheus
  - https://github.com/newrelic/nri-prometheus/tree/main/charts/nri-prometheus

version: 2.1.21
appVersion: 2.21.4

dependencies:
  - name: common-library
    version: 1.3.3
    repository: "https://helm-charts.newrelic.com"

maintainers:
  - name: alvarocabanas
    url: https://github.com/alvarocabanas
  - name: sigilioso
    url: https://github.com/sigilioso
  - name: gsanchezgavier
    url: https://github.com/gsanchezgavier
  - name: paologallinaharbur
    url: https://github.com/paologallinaharbur

keywords:
  - prometheus
  - newrelic
  - monitoring
