apiVersion: v2

name: nri-prometheus
description: A Helm chart to deploy the New Relic Prometheus OpenMetrics integration

home: https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-openmetrics/configure-prometheus-openmetrics-integrations/
icon: https://newrelic.com/themes/custom/curio/assets/mediakit/new_relic_logo_vertical.svg
sources:
  - https://github.com/newrelic/nri-prometheus

version: 2.1.0
appVersion: 2.14.0

keywords:
  - prometheus
  - newrelic
  - monitoring

dependencies:
  - name: common-library
    version: 1.0.1
    repository: "https://helm-charts.newrelic.com"

maintainers:
  - name: alvarocabanas
    url: https://github.com/alvarocabanas
  - name: carlossscastro
    url: https://github.com/carlossscastro
  - name: gsanchezgavier
    url: https://github.com/gsanchezgavier
  - name: kang-makes
    url: https://github.com/kang-makes
  - name: paologallinaharbur
    url: https://github.com/paologallinaharbur
  - name: roobre
    url: https://github.com/roobre
